server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.94.228.102:3306/second-hand?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: mysql
    druid:
      aop-patterns: com.qzx.secondhand.*
      filters: stat,wall
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: mysql
        reset-enable: false
      web-stat-filter:
        enabled: true
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 3000
        wall:
          enabled: true
          config:
            drop-table-allow: false

  redis:
    host: 47.94.228.102
    port: 6379
    password: redis